### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by Krogenar** [worldveil/deuces#13]
This is not an issue, so much as a question or request: How would you get or highlight just the cards that comprised the best hand for a player? So for example, say the player has what they need for a flush, how could I isolate just those cards from the total of 7 cards? Is there a way to do it from the library as it exists now? If not, any tips on how to achieve that?

**Comment by Krogenar** [comment]
I'm using this library to run a poker game within a text-based mud.
During the showdown, I display each player's hole cards and board cards together:
![showdown](https://cloud.githubusercontent.com/assets/23315560/21727018/31e04174-d40d-11e6-9c62-6e5b6cbe17a6.png)

What I'd like to do is figure some way to highlight the cards that make up the winning hand.
If I could do that, then I could modify the display above by either making each of the '5' cards shifted upwards to make them stand out. Or maybe put a colored 'V' over each.

Is this possible using this library? If not, any suggestions on where to start?

**Comment by worldveil** [comment]
For the coloring, I currently use `http://pypi.python.org/pypi/termcolor` for the red vs black, but of course for your highlighting you could use any colors. 

If performance isn't the issue here (doesn't seem to be, this is for a human player) then you could use Deuces to perform the evaluation and get the hand rank integer for 7 cards, and then compare for each (5 choose 7)  possibilities and then highlight the particular 5-set that matches the 7-set score. 

The `Evaluator` table logic already does this, so you could go from that code to create this or tweak it, etc.

**Comment by Krogenar** [comment]
Performance is not an issue -- deuces has been awesome. I will attempt to do what you've suggested, thanks for the quick response!
