### ISSUE TITLE
Why would these two hands evaluate to the same score?

### ISSUE THREAD

**Issue by Krogenar** [worldveil/deuces#14]
>>> import deuces
>>> from deuces import Card
>>> board = [Card.new('Jd'), Card.new('7h'), Card.new('Jc'), Card.new('Kh'), Card.new('Ks')]
>>> hand1 = [Card.new('Ah'), Card.new('8h')]
>>> hand2 = [Card.new('As'), Card.new('Qc')]
>>> from deuces import Evaluator
>>> evaluator = Evaluator()
>>> print evaluator.evaluate(board, hand1)
2611
>>> print evaluator.evaluate(board, hand2)
2611
>>>

Shouldn't hand2 be the stronger hand? Or does deuces pick the highest card only as the kicker?
According to this: https://en.wikipedia.org/wiki/Kicker_(poker) -- the second hole card should be considered as well, or am I missing something?

**Comment by n41r0j** [comment]
"Kickers always play unless the board makes a better hand than what either players have in their hands." In this case, the board has the best hands: Kings and Jacks have two pair. After that, the kicker comes into play, but, in the case you're describing, only one, since only the best 5 cards win. So the evaluation is right, K K J J A would be a split pot, and not a win for hand2, since the Q and 8 from both hands do not come into play.

**Comment by worldveil** [comment]
Yep, two-pair with ace kicker means the queen doesn't play.

**Comment by Krogenar** [comment]
Thank you for the quick response, and thank you for this very useful code!
